theme: jekyll-theme-cayman
title: "Pichai Nootor"
description: "Software Tester || Automate Tester | Mail: pichainootor@gmail | Phone: 095-395-5453"
# my_contact: "Mail pichainootor@gmail.com | Phone 095-395-5453"
# jekyll-theme-minimal 
# repository: pichai-nootor
# github_username: pichai-nootor
